FROM node:14

# Create app directory
WORKDIR /api

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)

COPY tsconfig.json /api/tsconfig.json 
COPY package.json /api/package.json
COPY package-lock.json /api/package-lock.json

# If you are building your code for production
# RUN npm ci --only=production
RUN npm install\
    && npm install typescript@4.1.6 -g

# Bundle app source
COPY . /api
