FROM node:14

# Create app directory
WORKDIR /api

COPY tsconfig.json /api/tsconfig.json 
COPY package.json /api/package.json
COPY package-lock.json /api/package-lock.json

RUN npm install\
    && npm install typescript@4.1.6 -g

# Bundle app source
COPY . /api
